// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '${{ secrets.WEB_KEY }}',
    appId: '1:2821174951:web:12cc2df8f1848b56fe8d82',
    messagingSenderId: '2821174951',
    projectId: 'team-coffee-b5a02',
    authDomain: 'team-coffee-b5a02.firebaseapp.com',
    storageBucket: 'team-coffee-b5a02.appspot.com',
    measurementId: 'G-C9NBZZS4DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '${{ secrets.ANDROID_KEY }}',
    appId: '1:2821174951:android:76a7b0d825f60325fe8d82',
    messagingSenderId: '2821174951',
    projectId: 'team-coffee-b5a02',
    storageBucket: 'team-coffee-b5a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${{ secrets.IOS_KEY }}',
    appId: '1:2821174951:ios:8362e236981242c1fe8d82',
    messagingSenderId: '2821174951',
    projectId: 'team-coffee-b5a02',
    storageBucket: 'team-coffee-b5a02.appspot.com',
    iosBundleId: 'com.example.teamCoffee',
  );

}
